# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: CI
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_PUBLISH: 'off'
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run jest
      - run: npm run eslint
      - run: npm run build
      - run: npm publish
        if: env.IS_PUBLISH == 'on'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
