on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: '是否发布'
        required: true
        default: 'warning'
        type: choice
        options:
        - on
        - off



jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
        env:
          LEVEL: ${{ inputs.logLevel }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm publish
        if: env.LEVEL == 'on'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
